spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/pocketr_db
    username: ${DB_USER:pocketr_user}
    password: ${DB_PASSWORD:pocketr_password}

server:
  port: 8081
  servlet:
    session:
      cookie:
        path: /

app:
  security:
    csrf-cookie-path: /

pocketr:
  avatar:
    storage-dir: storage/avatars
